[package]
name = "user_creation"
version = "0.1.0"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
sha2 = "0.10"
uuid =  { version = "0.8", features = ["v4"] }